### PR TITLE
[0011] Clarify behavior of SpirvType parameters and add SpirvOpaqueType

### LINKED ISSUE #128: [0011] Enable vk::SpirvType to be used in interface arrays and structs
**Which proposal does this relate to?**

[0011: Inline SPIR-V](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0011-inline-spirv.md)

**Describe the issue or outstanding question.**

The compiler does not know the size or alignment of a `vk::SpirvType`. Because types that are used in an interface variables like globals or structured buffers must be fully laid out, the compiler needs to know the size and alignment of a `vk:SpirvType` if it is used in an aggregate type that is part of the interface.

**Additional context**

We might need to think how this will interact with the different layout rules that we support.

### PR DESCRIPTION
**Pull request by cassiebeckley**
`SpirvType` now takes size and alignment as parameters, and a new template `SpirvOpaqueType` is added that does not. Also lets users specify whether a parameter for the type-declaration instruction should take an id or an immediate literal value.

Fixes #128.

### CODE REVIEW

**Comment by cassiebeckley** [comment]
@s-perron

**Review by s-perron — APPROVED** [review]

**Comment by s-perron** [comment]
This is a pretty big change to the original proposal, but necessary to do what we need to do.

**Review by llvm-beanz — APPROVED** [review]
I think this LGTM. I wonder if there is some alignment we should aim for between this proposal and https://github.com/microsoft/hlsl-specs/pull/154.

**Comment by cassiebeckley** [comment]
I'd considered using `alignas`, but it would require modifying the parser to have a different behavior than C++, which we were trying to avoid for the most part.

For example

```hlsl
typedef alignas(8) vk::SpirvType</* OpTypeInt */ 21, /* size */ 8, vk::ext_literal(8), vk::ext_literal(false)> uint8_t;
```

or

```hlsl
typedef vk::SpirvType</* OpTypeInt */ 21, /* size */ 8, vk::ext_literal(8), vk::ext_literal(false)> alignas(8) uint8_t;
```

would not be valid syntax.

**Comment by llvm-beanz** [comment]
Right... because `alignas` isn't valid for typedefs :(

That said, we might be able to implement this feature in terms of `alignas` in the future because this horrible thing is completely valid (with C23):

```c++
template<int Align, int Size>
struct alignas(Align) OpaqueType
{
  _BitInt(Size) V;
};
```

**Pull request merged**
